# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0010_auto_20170815_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='intent_robustness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
