# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0011_utterance_intent_robustness'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='intent_robustness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
